#!/usr/bin/env ruby

$: << 'lib'
$stderr.sync = $stdout.sync = true

require 'bundler/setup'
require 'guardian/worker'

trap('INT')  { exit }
trap('TERM') { @worker.stop }
@worker = Guardian::Worker.new
@worker.start
