#!/usr/bin/env ruby

$: << 'lib'
$stderr.sync = $stdout.sync = true

require 'bundler/setup'
require 'guardian/worker'

trap('INT')  { exit }
trap('TERM') { @worker.stop; exit }

at_exit do
  if $! && !$!.is_a?(SystemExit)
    # TODO: Better error message
    $stderr.puts "Unhandled Error: #{$!.inspect} #{$@}"
  end
end

@worker = Guardian::Worker.new
@worker.start
